-- ============================================================
-- SIGA - Migracion del inventario de equipos de computacion
-- Fuente: PDF "INVENTARIO DE EQUIPOS DE COMPUTACION - ICACRUZ" (94 paginas)
-- Genera 274 bienes en 26 areas.
--
-- Como ejecutar: Supabase -> SQL Editor -> New query -> pegar todo -> Run.
-- Requiere que 01_estructura.sql ya este aplicado (usa las 21 categorias).
-- El codigo de cada bien (ICA-XXX-0000) lo genera el trigger, no este script.
-- Es seguro: si se ejecuta dos veces, la segunda aborta sin insertar nada.
-- ============================================================

-- ------------------------------------------------------------
-- 1. Catalogos: areas y responsables que aparecen en el PDF
-- ------------------------------------------------------------
insert into public.ubicaciones (nombre) values
  ('APOYO AL ICACRUZ'),
  ('ARCHIVO'),
  ('AUXILIAR CONTABLE-1'),
  ('AUXILIAR CONTABLE-2'),
  ('BIBLIOTECA'),
  ('CAJA AFILIACION'),
  ('CENTRAL DE REDES - SERVIDOR'),
  ('COBRANZAS-1'),
  ('COBRANZAS-2'),
  ('COBRANZAS-3'),
  ('COBRANZAS-4'),
  ('COBRANZAS-5'),
  ('COCINA'),
  ('CONTABILIDAD - SERVIDOR'),
  ('EPJ-GP'),
  ('GERENCIA'),
  ('GERENTE ADMINISTRATIVO'),
  ('MARKETING'),
  ('PRESIDENCIA'),
  ('RECEPCION'),
  ('SALON AUDITORIO'),
  ('SECRETARIA DE EPJ-GP'),
  ('SECRETARIA DE GERENCIA'),
  ('SECRETARIA DE PRESIDENCIA'),
  ('TRIBUNAL DE HONOR'),
  ('TRIBUNAL DE HONOR-2')
on conflict (nombre) do nothing;

insert into public.responsables (nombre) values
  ('ALISSON VARGAS'),
  ('CATALINA GALVEZ'),
  ('CELESTE'),
  ('DR. CLOVIS SUAREZ'),
  ('DR. JULIO EGUEZ'),
  ('DR. JUSTO SAAVEDRA'),
  ('DRA. LEONILDA'),
  ('DRA. MARIANA'),
  ('DRA. NOELIA SORETA'),
  ('EDUARDO SILES'),
  ('ING. BRENDA CORTEZ'),
  ('JACLYN REBOLLEDO'),
  ('JOSUE'),
  ('LIC. ANTONIO AGUILERA'),
  ('LIC. CARMEN SUAREZ'),
  ('LIC. JOEL CHANEZ'),
  ('LIC. MARISOL CHOQUE'),
  ('MARIELA PRADO'),
  ('ROXANA VACA'),
  ('ROY MORENO'),
  ('SRA. CECILIA VACA')
on conflict (nombre) do nothing;

-- ------------------------------------------------------------
-- 2. Bienes
--
--    Se insertan de a uno dentro de un bucle, y no con un INSERT masivo,
--    porque generar_codigo() consulta el maximo correlativo de la categoria:
--    en un INSERT de varias filas todas leerian el mismo maximo y chocarian
--    contra el unique de codigo.
-- ------------------------------------------------------------
do $$
declare
  r        record;
  v_id     bigint;
  v_total  int := 0;
begin
  if exists (select 1 from public.activos where creado_por = 'MIGRACION-COMPUTACION-2026') then
    raise exception 'La migracion ya fue ejecutada. Para rehacerla, borre primero los bienes cuyo creado_por sea MIGRACION-COMPUTACION-2026';
  end if;

  for r in
    select * from (values
      (   1, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 10 PRO DE 64 BITS; PROCESADOR INTEL CORE 2 DUO DE 3.00 GHZ; MEMORIA RAM 8GB; DISCO SOLIDO KINGSTON 480 GB', 'EPJ-GP', 'EDUARDO SILES', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 1'),
      (   2, 'MON', 'Monitor', 'Samsung', '19"', '', 'EPJ-GP', 'EDUARDO SILES', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 1'),
      (   3, 'TEC', 'Mouse', 'Delux', '', '', 'EPJ-GP', 'EDUARDO SILES', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 1'),
      (   4, 'TEC', 'Teclado', 'Delux', '', '', 'EPJ-GP', 'EDUARDO SILES', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 1'),
      (   5, 'IMP', 'Impresora', 'Epson', 'L4150 WIFI', '', 'EPJ-GP', 'EDUARDO SILES', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 1'),
      (   6, 'TEC', 'Parlantes', 'Delux', '', '', 'EPJ-GP', 'EDUARDO SILES', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 1'),
      (   7, 'UPS', 'Estabilizador', 'SmartBitt', '8 SALIDAS', '', 'EPJ-GP', 'EDUARDO SILES', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 1'),
      (   8, 'TEC', 'Parlante', 'DJV', '', '', 'EPJ-GP', 'EDUARDO SILES', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 1'),
      (   9, 'PRY', 'Radio', 'Sony', '', '', 'EPJ-GP', 'EDUARDO SILES', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 1'),
      (  10, 'TEL', 'Telefono', 'Panasonic', '', 'Color negro', 'EPJ-GP', 'EDUARDO SILES', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 1'),
      (  11, 'TEL', 'Celular corporativo', 'Samsung', 'Galaxy A15', '', 'EPJ-GP', 'EDUARDO SILES', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 1. REVISAR: el PDF dice ''CORPORATIVO 2 SAMSUNG GALAXY A15''; se interpreto como dos equipos. Unidad 1 de 2 del mismo renglon'),
      (  12, 'TEL', 'Celular corporativo', 'Samsung', 'Galaxy A15', '', 'EPJ-GP', 'EDUARDO SILES', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 1. REVISAR: el PDF dice ''CORPORATIVO 2 SAMSUNG GALAXY A15''; se interpreto como dos equipos. Unidad 2 de 2 del mismo renglon'),
      (  13, 'LPT', 'Laptop', 'HP', '', 'WINDOWS WINDOWS 11 PRO DE 64 BITS; PROCESADOR INTEL CORE I3-1315U DE 1.20 GHZ; MEMORIA RAM 8GB; DISCO M2 500 GB', 'SECRETARIA DE EPJ-GP', 'MARIELA PRADO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 5'),
      (  14, 'TEC', 'Mouse', 'Unlook', '', '', 'SECRETARIA DE EPJ-GP', 'MARIELA PRADO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 5'),
      (  15, 'TEL', 'Telefono', 'Panasonic', '', 'Color negro', 'SECRETARIA DE EPJ-GP', 'MARIELA PRADO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 5'),
      (  16, 'MON', 'Monitor', 'AOC', '', '', 'SECRETARIA DE EPJ-GP', 'MARIELA PRADO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 5'),
      (  17, 'TEC', 'Teclado', 'Genius', '', '', 'SECRETARIA DE EPJ-GP', 'MARIELA PRADO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 5'),
      (  18, 'CPU', 'CPU de escritorio', '', '', '', 'SECRETARIA DE EPJ-GP', 'MARIELA PRADO', 'Malo', 'Migrado del PDF de inventario de computacion, pag. 5. NO SIRVE la tarjeta madre segun el PDF'),
      (  19, 'PRY', 'Proyector', 'Epson', 'X41+', '', 'SECRETARIA DE EPJ-GP', 'MARIELA PRADO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 5'),
      (  20, 'PRY', 'Tripode', '', '', '', 'SECRETARIA DE EPJ-GP', 'MARIELA PRADO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 5'),
      (  21, 'CAM', 'Camara', 'Hikvision', '', '', 'SECRETARIA DE EPJ-GP', 'MARIELA PRADO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 5'),
      (  22, 'TEC', 'Cable HDMI', '', '', '', 'SECRETARIA DE EPJ-GP', 'MARIELA PRADO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 5'),
      (  23, 'TEC', 'Hub USB', '', '', '', 'SECRETARIA DE EPJ-GP', 'MARIELA PRADO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 5'),
      (  24, 'PRY', 'Microfono', '', '', '', 'SECRETARIA DE EPJ-GP', 'MARIELA PRADO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 5'),
      (  25, 'PRY', 'Puntero presentador', '', '', '', 'SECRETARIA DE EPJ-GP', 'MARIELA PRADO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 5'),
      (  26, 'LPT', 'Laptop', 'HP', '', 'WINDOWS WINDOWS 11 PRO DE 64 BITS; PROCESADOR INTEL CORE I3-1315U DE 1.20 GHZ; MEMORIA RAM 8GB; DISCO M2 500 GB', 'BIBLIOTECA', 'CATALINA GALVEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 10'),
      (  27, 'TEC', 'Mouse', 'Knup', '', '', 'BIBLIOTECA', 'CATALINA GALVEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 10'),
      (  28, 'IMP', 'Impresora de adhesivos', '', 'TERMICA LABEL PRINTER', '', 'BIBLIOTECA', 'CATALINA GALVEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 10'),
      (  29, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 7 ULTIMATE DE 64 BITS; PROCESADOR INTEL PENTIUM CPU G620 DE 2.60 GHZ; MEMORIA RAM 2GB; DISCO DURO 500 GB', 'RECEPCION', 'DR. JUSTO SAAVEDRA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 12'),
      (  30, 'MON', 'Monitor', 'Samsung', '19"', '', 'RECEPCION', 'DR. JUSTO SAAVEDRA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 12'),
      (  31, 'TEC', 'Mouse', 'Delux', '', '', 'RECEPCION', 'DR. JUSTO SAAVEDRA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 12'),
      (  32, 'TEC', 'Teclado', 'Delux', '', '', 'RECEPCION', 'DR. JUSTO SAAVEDRA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 12'),
      (  33, 'TEL', 'Telefono', 'Panasonic', 'KX-DT543 CENTRAL', '', 'RECEPCION', 'DR. JUSTO SAAVEDRA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 12'),
      (  34, 'UPS', 'Regleta', 'Forza', '', '', 'RECEPCION', 'DR. JUSTO SAAVEDRA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 12'),
      (  35, 'LPT', 'Laptop', 'HP', '245 G7', 'WINDOWS WINDOWS 10 PRO DE 64 BITS; PROCESADOR AMD RYZEN 3-3250U DE 2.60 GHZ; MEMORIA RAM 8GB; DISCO SOLIDO KINGSTON 980 GB; TARJETA DE VIDEO AMD RADEON VEGA 3 DE 2GB', 'GERENCIA', 'DR. CLOVIS SUAREZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 14'),
      (  36, 'TEL', 'Telefono', 'Panasonic', 'KX-FT988', '', 'GERENCIA', 'DR. CLOVIS SUAREZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 14'),
      (  37, 'IMP', 'Impresora', 'HP', 'LASEJET P1102w', '', 'GERENCIA', 'DR. CLOVIS SUAREZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 14'),
      (  38, 'UPS', 'Estabilizador', 'Forza', '1200 VA', '', 'GERENCIA', 'DR. CLOVIS SUAREZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 14'),
      (  39, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 10 PRO DE 64 BITS; PROCESADOR INTEL PENTIUM CPU G2030 DE 3.00 GHZ; MEMORIA RAM 6GB; DISCO SOLIDO KINGSTON 480 GB; TARJETA DE VIDEO NVIDIA GEFORCE 210 DE 973 MB', 'SECRETARIA DE GERENCIA', 'DRA. NOELIA SORETA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 17'),
      (  40, 'MON', 'Monitor', 'Samsung', '19"', '', 'SECRETARIA DE GERENCIA', 'DRA. NOELIA SORETA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 17'),
      (  41, 'TEC', 'Mouse', 'Genius', '', '', 'SECRETARIA DE GERENCIA', 'DRA. NOELIA SORETA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 17'),
      (  42, 'TEC', 'Teclado', 'Knup', 'INALAMBRICO', '', 'SECRETARIA DE GERENCIA', 'DRA. NOELIA SORETA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 17'),
      (  43, 'TEL', 'Telefono', 'Panasonic', 'KX-FT988', '', 'SECRETARIA DE GERENCIA', 'DRA. NOELIA SORETA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 17'),
      (  44, 'IMP', 'Impresora', 'Epson', 'WF-C5710', '', 'SECRETARIA DE GERENCIA', 'DRA. NOELIA SORETA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 17'),
      (  45, 'UPS', 'Regleta', 'Forza', '', '', 'SECRETARIA DE GERENCIA', 'DRA. NOELIA SORETA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 17'),
      (  46, 'UPS', 'Regleta', 'GCR', '', '', 'SECRETARIA DE GERENCIA', 'DRA. NOELIA SORETA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 17'),
      (  47, 'TEL', 'Celular corporativo', 'Samsung', 'GALAXY A03', '', 'SECRETARIA DE GERENCIA', 'DRA. NOELIA SORETA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 17'),
      (  48, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 10 PRO DE 64 BITS; PROCESADOR INTEL CORE I3 4130T DE 2.90 GHZ; MEMORIA RAM 4GB; DISCO SOLIDO KINGSTON 480 GB', 'MARKETING', 'ROXANA VACA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 20'),
      (  49, 'MON', 'Monitor', 'Samsung', '19"', '', 'MARKETING', 'ROXANA VACA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 20'),
      (  50, 'TEC', 'Mouse', 'Knup', '', '', 'MARKETING', 'ROXANA VACA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 20'),
      (  51, 'TEC', 'Teclado', '', 'GAME & MX', '', 'MARKETING', 'ROXANA VACA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 20'),
      (  52, 'TEL', 'Telefono', 'Panasonic', '', '', 'MARKETING', 'ROXANA VACA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 20'),
      (  53, 'IMP', 'Impresora', 'Epson', 'L3210', '', 'MARKETING', 'ROXANA VACA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 20'),
      (  54, 'UPS', 'Regleta', 'Forza', '', '', 'MARKETING', 'ROXANA VACA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 20'),
      (  55, 'RED', 'Router', 'TP-Link', '2 ANTENAS DE 300 MBPS', '', 'MARKETING', 'ROXANA VACA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 20'),
      (  56, 'TEL', 'Celular corporativo', '', '', '', 'MARKETING', 'ROXANA VACA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 20. El PDF no indica marca ni modelo'),
      (  57, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 11 PRO DE 64 BITS; PROCESADOR INTEL CORE I7-11700 DE 2.50 GHZ; MEMORIA RAM 32GB; DISCO SOLIDO 980 GB; TARJETA DE VIDEO NVIDIA GEFORCE RTX 3050 DE 8GB', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23'),
      (  58, 'MON', 'Monitor', 'Asus', '24"', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23'),
      (  59, 'TEC', 'Mouse', 'Genius', '', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23'),
      (  60, 'TEC', 'Teclado', 'Delux', '', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23'),
      (  61, 'TEC', 'Hub USB', '', 'LECTOR DE TARJETA SD', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23'),
      (  62, 'UPS', 'Regleta', 'Forza', '', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23. Unidad 1 de 2 del mismo renglon'),
      (  63, 'UPS', 'Regleta', 'Forza', '', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23. Unidad 2 de 2 del mismo renglon'),
      (  64, 'PRY', 'Tripode', '', '', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23. Unidad 1 de 2 del mismo renglon'),
      (  65, 'PRY', 'Tripode', '', '', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23. Unidad 2 de 2 del mismo renglon'),
      (  66, 'PRY', 'Luz LED', 'Huavi', '', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23. Unidad 1 de 3 del mismo renglon'),
      (  67, 'PRY', 'Luz LED', 'Huavi', '', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23. Unidad 2 de 3 del mismo renglon'),
      (  68, 'PRY', 'Luz LED', 'Huavi', '', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23. Unidad 3 de 3 del mismo renglon'),
      (  69, 'PRY', 'Aro de luz', '', '', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23'),
      (  70, 'PRY', 'Luz LED portatil', '', '', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23'),
      (  71, 'PRY', 'Microfono inalambrico', 'Eletro', '', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23. El PDF lo escribe en plural sin indicar cantidad'),
      (  72, 'PRY', 'Camara fotografica', 'Nikon', 'D3500', '', 'MARKETING', 'ROY MORENO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 23'),
      (  73, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 10 PRO DE 64 BITS; PROCESADOR INTEL CORE I5-10400 DE 2.90 GHZ; MEMORIA RAM 16GB; DISCO SOLIDO KINGSTON 980 GB', 'CAJA AFILIACION', 'LIC. MARISOL CHOQUE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 29'),
      (  74, 'MON', 'Monitor', 'Samsung', '22"', '', 'CAJA AFILIACION', 'LIC. MARISOL CHOQUE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 29'),
      (  75, 'TEC', 'Mouse', 'Unlook', '', '', 'CAJA AFILIACION', 'LIC. MARISOL CHOQUE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 29'),
      (  76, 'TEC', 'Teclado', 'Tecson', '', '', 'CAJA AFILIACION', 'LIC. MARISOL CHOQUE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 29'),
      (  77, 'TEL', 'Telefono', 'Panasonic', '', '', 'CAJA AFILIACION', 'LIC. MARISOL CHOQUE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 29'),
      (  78, 'IMP', 'Impresora de credenciales', 'Epson', 'L8050', '', 'CAJA AFILIACION', 'LIC. MARISOL CHOQUE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 29'),
      (  79, 'IMP', 'Impresora', 'HP', 'LASERJET P1102w', '', 'CAJA AFILIACION', 'LIC. MARISOL CHOQUE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 29'),
      (  80, 'UPS', 'Estabilizador', 'Forza', '', '', 'CAJA AFILIACION', 'LIC. MARISOL CHOQUE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 29'),
      (  81, 'UPS', 'Regleta', 'Forza', '', '', 'CAJA AFILIACION', 'LIC. MARISOL CHOQUE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 29'),
      (  82, 'TEL', 'Celular corporativo', 'Samsung', 'GALAXY A24', '', 'CAJA AFILIACION', 'LIC. MARISOL CHOQUE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 29'),
      (  83, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 10 PRO DE 64 BITS; PROCESADOR INTEL CORE I3-4130T DE 2.90 GHZ; MEMORIA RAM 4GB; DISCO SOLIDO KINGSTON 480 GB', 'APOYO AL ICACRUZ', 'JACLYN REBOLLEDO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 32'),
      (  84, 'MON', 'Monitor', 'Samsung', '19"', '', 'APOYO AL ICACRUZ', 'JACLYN REBOLLEDO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 32'),
      (  85, 'TEC', 'Mouse', 'Logitech', 'INALABRICO', '', 'APOYO AL ICACRUZ', 'JACLYN REBOLLEDO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 32'),
      (  86, 'TEC', 'Teclado', 'Logitech', 'INALAMBRICO', '', 'APOYO AL ICACRUZ', 'JACLYN REBOLLEDO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 32'),
      (  87, 'IMP', 'Impresora', 'HP', 'LASERJET M1132 MFP', '', 'APOYO AL ICACRUZ', 'JACLYN REBOLLEDO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 32'),
      (  88, 'UPS', 'Regleta', 'Forza', '', '', 'APOYO AL ICACRUZ', 'JACLYN REBOLLEDO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 32'),
      (  89, 'UPS', 'Regleta', 'Rowland', '', '', 'APOYO AL ICACRUZ', 'JACLYN REBOLLEDO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 32'),
      (  90, 'RED', 'Switch', 'TP-Link', '16 PUERTOS 10/100', '', 'APOYO AL ICACRUZ', 'JACLYN REBOLLEDO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 32'),
      (  91, 'UPS', 'Regleta', 'Forza', '', '', 'APOYO AL ICACRUZ', 'JACLYN REBOLLEDO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 32'),
      (  92, 'PRY', 'Microfono', '', 'GIRAFA', '', 'APOYO AL ICACRUZ', 'JACLYN REBOLLEDO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 32. Unidad 1 de 4 del mismo renglon'),
      (  93, 'PRY', 'Microfono', '', 'GIRAFA', '', 'APOYO AL ICACRUZ', 'JACLYN REBOLLEDO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 32. Unidad 2 de 4 del mismo renglon'),
      (  94, 'PRY', 'Microfono', '', 'GIRAFA', '', 'APOYO AL ICACRUZ', 'JACLYN REBOLLEDO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 32. Unidad 3 de 4 del mismo renglon'),
      (  95, 'PRY', 'Microfono', '', 'GIRAFA', '', 'APOYO AL ICACRUZ', 'JACLYN REBOLLEDO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 32. Unidad 4 de 4 del mismo renglon'),
      (  96, 'PRY', 'Microfono', 'Shure', 'INALAMBRICO', '', 'APOYO AL ICACRUZ', 'JACLYN REBOLLEDO', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 32'),
      (  97, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 10 PRO DE 64 BITS; PROCESADOR INTEL CORE I7-4790 DE 3.60 GHZ; MEMORIA RAM 8GB; DISCO SOLIDO KINGSTON 480 GB', 'GERENTE ADMINISTRATIVO', 'LIC. JOEL CHANEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 35'),
      (  98, 'MON', 'Monitor', 'AOC', '23"', '', 'GERENTE ADMINISTRATIVO', 'LIC. JOEL CHANEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 35'),
      (  99, 'TEC', 'Mouse', 'Logitech', 'INALABRICO', '', 'GERENTE ADMINISTRATIVO', 'LIC. JOEL CHANEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 35'),
      ( 100, 'TEC', 'Teclado', 'Logitech', 'INALAMBRICO', '', 'GERENTE ADMINISTRATIVO', 'LIC. JOEL CHANEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 35'),
      ( 101, 'TEL', 'Telefono', 'Panasonic', 'KX-T7630 - BLANCO', '', 'GERENTE ADMINISTRATIVO', 'LIC. JOEL CHANEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 35'),
      ( 102, 'IMP', 'Impresora', 'Canon', 'G2100', '', 'GERENTE ADMINISTRATIVO', 'LIC. JOEL CHANEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 35'),
      ( 103, 'IMP', 'Impresora', 'Brother', 'MFC-L5900DW', '', 'GERENTE ADMINISTRATIVO', 'LIC. JOEL CHANEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 35'),
      ( 104, 'UPS', 'Estabilizador', 'Forza', '1200 VA', '', 'GERENTE ADMINISTRATIVO', 'LIC. JOEL CHANEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 35'),
      ( 105, 'UPS', 'Regleta', 'Forza', '', '', 'GERENTE ADMINISTRATIVO', 'LIC. JOEL CHANEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 35'),
      ( 106, 'TEC', 'Parlante', 'Bose', '', '', 'GERENTE ADMINISTRATIVO', 'LIC. JOEL CHANEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 35'),
      ( 107, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 11 PRO DE 64 BITS; PROCESADOR INTEL CORE I5-10400 DE 2.90 GHZ; MEMORIA RAM 8GB; DISCO SOLIDO KINGSTON 480 GB', 'AUXILIAR CONTABLE-1', 'LIC. ANTONIO AGUILERA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 40'),
      ( 108, 'MON', 'Monitor', 'Samsung', '22"', '', 'AUXILIAR CONTABLE-1', 'LIC. ANTONIO AGUILERA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 40'),
      ( 109, 'TEC', 'Mouse', 'Delux', '', '', 'AUXILIAR CONTABLE-1', 'LIC. ANTONIO AGUILERA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 40'),
      ( 110, 'TEC', 'Teclado', 'Delux', '', '', 'AUXILIAR CONTABLE-1', 'LIC. ANTONIO AGUILERA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 40'),
      ( 111, 'IMP', 'Impresora', 'HP', 'LASERJET MFP M130FW', '', 'AUXILIAR CONTABLE-1', 'LIC. ANTONIO AGUILERA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 40'),
      ( 112, 'RED', 'Switch', 'TP-Link', 'GIGABIT 10/100/1.000', '', 'AUXILIAR CONTABLE-1', 'LIC. ANTONIO AGUILERA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 40'),
      ( 113, 'UPS', 'Regleta', 'Volt', '', '', 'AUXILIAR CONTABLE-1', 'LIC. ANTONIO AGUILERA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 40'),
      ( 114, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 10 PRO DE 64 BITS; PROCESADOR INTEL CORE I3-2120 DE 3.30 GHZ; MEMORIA RAM 4GB; DISCO SOLIDO KINGSTON 480 GB', 'AUXILIAR CONTABLE-2', 'LIC. CARMEN SUAREZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 43'),
      ( 115, 'MON', 'Monitor', 'LG', '20"', '', 'AUXILIAR CONTABLE-2', 'LIC. CARMEN SUAREZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 43'),
      ( 116, 'TEC', 'Mouse', 'Genius', '', '', 'AUXILIAR CONTABLE-2', 'LIC. CARMEN SUAREZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 43'),
      ( 117, 'TEC', 'Teclado', 'Knup', '', '', 'AUXILIAR CONTABLE-2', 'LIC. CARMEN SUAREZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 43'),
      ( 118, 'UPS', 'Regleta', 'Forza', '', '', 'AUXILIAR CONTABLE-2', 'LIC. CARMEN SUAREZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 43'),
      ( 119, 'SRV', 'Servidor', '', '', 'WINDOWS WINDOWS SERVER 2016 DE 64 BITS; PROCESADOR INTEL CORE I5-4460 DE 3.20 GHZ; MEMORIA RAM 8GB; DISCO SOLIDO KINGSTON 960 GB', 'CONTABILIDAD - SERVIDOR', 'LIC. JOEL CHANEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 45'),
      ( 120, 'CAB', 'Rack', '', 'METALICO DE 42U', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46'),
      ( 121, 'CAB', 'Patch panel', 'Next', '24 PUERTOS CAT5E', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 1 de 2 del mismo renglon'),
      ( 122, 'CAB', 'Patch panel', 'Next', '24 PUERTOS CAT5E', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 2 de 2 del mismo renglon'),
      ( 123, 'RED', 'Switch', 'TP-Link', 'TL-SG1024 DE 24 PUERTOS GIGABIT', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46'),
      ( 124, 'RED', 'Switch', 'Cisco', 'CATALYST 2950 DE 24 PUERTOS 10/100', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46'),
      ( 125, 'RED', 'Switch', 'TP-Link', '16 PUERTOS 10/100', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46'),
      ( 126, 'RED', 'Modem', 'Arris', 'TIGO DG3450', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46'),
      ( 127, 'RED', 'Modem', 'Huawei', 'COTAS GPON ONU', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46'),
      ( 128, 'RED', 'Switch', 'Grandstream', 'COTAS PARA TELEFONOS', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46'),
      ( 129, 'RED', 'Router', 'TP-Link', 'AX20', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46'),
      ( 130, 'UPS', 'UPS', 'Forza', '500VA/250W', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46'),
      ( 131, 'UPS', 'Regleta', '', '', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Marcas Forza y Volt; el PDF no detalla cuantas de cada una. Unidad 1 de 7 del mismo renglon'),
      ( 132, 'UPS', 'Regleta', '', '', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Marcas Forza y Volt; el PDF no detalla cuantas de cada una. Unidad 2 de 7 del mismo renglon'),
      ( 133, 'UPS', 'Regleta', '', '', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Marcas Forza y Volt; el PDF no detalla cuantas de cada una. Unidad 3 de 7 del mismo renglon'),
      ( 134, 'UPS', 'Regleta', '', '', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Marcas Forza y Volt; el PDF no detalla cuantas de cada una. Unidad 4 de 7 del mismo renglon'),
      ( 135, 'UPS', 'Regleta', '', '', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Marcas Forza y Volt; el PDF no detalla cuantas de cada una. Unidad 5 de 7 del mismo renglon'),
      ( 136, 'UPS', 'Regleta', '', '', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Marcas Forza y Volt; el PDF no detalla cuantas de cada una. Unidad 6 de 7 del mismo renglon'),
      ( 137, 'UPS', 'Regleta', '', '', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Marcas Forza y Volt; el PDF no detalla cuantas de cada una. Unidad 7 de 7 del mismo renglon'),
      ( 138, 'CAM', 'DVR', 'Dahua', '16 CH', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46'),
      ( 139, 'CAM', 'Camara de seguridad', '', 'ANALOGICAS Y HD', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 1 de 14 del mismo renglon'),
      ( 140, 'CAM', 'Camara de seguridad', '', 'ANALOGICAS Y HD', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 2 de 14 del mismo renglon'),
      ( 141, 'CAM', 'Camara de seguridad', '', 'ANALOGICAS Y HD', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 3 de 14 del mismo renglon'),
      ( 142, 'CAM', 'Camara de seguridad', '', 'ANALOGICAS Y HD', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 4 de 14 del mismo renglon'),
      ( 143, 'CAM', 'Camara de seguridad', '', 'ANALOGICAS Y HD', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 5 de 14 del mismo renglon'),
      ( 144, 'CAM', 'Camara de seguridad', '', 'ANALOGICAS Y HD', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 6 de 14 del mismo renglon'),
      ( 145, 'CAM', 'Camara de seguridad', '', 'ANALOGICAS Y HD', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 7 de 14 del mismo renglon'),
      ( 146, 'CAM', 'Camara de seguridad', '', 'ANALOGICAS Y HD', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 8 de 14 del mismo renglon'),
      ( 147, 'CAM', 'Camara de seguridad', '', 'ANALOGICAS Y HD', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 9 de 14 del mismo renglon'),
      ( 148, 'CAM', 'Camara de seguridad', '', 'ANALOGICAS Y HD', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 10 de 14 del mismo renglon'),
      ( 149, 'CAM', 'Camara de seguridad', '', 'ANALOGICAS Y HD', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 11 de 14 del mismo renglon'),
      ( 150, 'CAM', 'Camara de seguridad', '', 'ANALOGICAS Y HD', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 12 de 14 del mismo renglon'),
      ( 151, 'CAM', 'Camara de seguridad', '', 'ANALOGICAS Y HD', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 13 de 14 del mismo renglon'),
      ( 152, 'CAM', 'Camara de seguridad', '', 'ANALOGICAS Y HD', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 14 de 14 del mismo renglon'),
      ( 153, 'UPS', 'Fuente de poder', '', 'METALICA 12V - 10AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46'),
      ( 154, 'UPS', 'Fuente de poder', '', '12V-3AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 1 de 3 del mismo renglon'),
      ( 155, 'UPS', 'Fuente de poder', '', '12V-3AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 2 de 3 del mismo renglon'),
      ( 156, 'UPS', 'Fuente de poder', '', '12V-3AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 3 de 3 del mismo renglon'),
      ( 157, 'CAM', 'XVR', 'Dahua', '16 CH', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46'),
      ( 158, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 1 de 16 del mismo renglon'),
      ( 159, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 2 de 16 del mismo renglon'),
      ( 160, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 3 de 16 del mismo renglon'),
      ( 161, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 4 de 16 del mismo renglon'),
      ( 162, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 5 de 16 del mismo renglon'),
      ( 163, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 6 de 16 del mismo renglon'),
      ( 164, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 7 de 16 del mismo renglon'),
      ( 165, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 8 de 16 del mismo renglon'),
      ( 166, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 9 de 16 del mismo renglon'),
      ( 167, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 10 de 16 del mismo renglon'),
      ( 168, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 11 de 16 del mismo renglon'),
      ( 169, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 12 de 16 del mismo renglon'),
      ( 170, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 13 de 16 del mismo renglon'),
      ( 171, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 14 de 16 del mismo renglon'),
      ( 172, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 15 de 16 del mismo renglon'),
      ( 173, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 16 de 16 del mismo renglon'),
      ( 174, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 1 de 16 del mismo renglon'),
      ( 175, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 2 de 16 del mismo renglon'),
      ( 176, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 3 de 16 del mismo renglon'),
      ( 177, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 4 de 16 del mismo renglon'),
      ( 178, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 5 de 16 del mismo renglon'),
      ( 179, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 6 de 16 del mismo renglon'),
      ( 180, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 7 de 16 del mismo renglon'),
      ( 181, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 8 de 16 del mismo renglon'),
      ( 182, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 9 de 16 del mismo renglon'),
      ( 183, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 10 de 16 del mismo renglon'),
      ( 184, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 11 de 16 del mismo renglon'),
      ( 185, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 12 de 16 del mismo renglon'),
      ( 186, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 13 de 16 del mismo renglon'),
      ( 187, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 14 de 16 del mismo renglon'),
      ( 188, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 15 de 16 del mismo renglon'),
      ( 189, 'UPS', 'Fuente de poder', '', 'INDEPENDIENTE 12V - 1AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 16 de 16 del mismo renglon'),
      ( 190, 'CAM', 'XVR', 'Dahua', '8 CH', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46'),
      ( 191, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 1 de 3 del mismo renglon'),
      ( 192, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 2 de 3 del mismo renglon'),
      ( 193, 'CAM', 'Camara de seguridad', '', 'DOMO FULL HD 1080P', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46. Unidad 3 de 3 del mismo renglon'),
      ( 194, 'UPS', 'Fuente de poder', '', 'METALICA 12V - 15AMP', '', 'CENTRAL DE REDES - SERVIDOR', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 46'),
      ( 195, 'LPT', 'Laptop', 'HP', '250 DE 15.6 PULGADAS', 'WINDOWS WINDOWS 11 PRO DE 64 BITS; PROCESADOR INTEL CORE I3-1315U DE 1.20 GHZ; MEMORIA RAM 8GB; DISCO SOLIDO 500 GB', 'ARCHIVO', 'JOSUE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 51'),
      ( 196, 'TEC', 'Mouse', 'Genius', '', '', 'ARCHIVO', 'JOSUE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 51'),
      ( 197, 'IMP', 'Escaner', 'Brother', 'ADS-2400N', '', 'ARCHIVO', 'JOSUE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 51'),
      ( 198, 'UPS', 'Regleta', 'Forza', '', '', 'ARCHIVO', 'JOSUE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 51'),
      ( 199, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 7 PRO DE 64 BITS; PROCESADOR INTEL CORE I3-1315U DE 1.20 GHZ; MEMORIA RAM 4GB; DISCO DURO MAL ESTADO', 'ARCHIVO', '', 'Malo', 'Migrado del PDF de inventario de computacion, pag. 53'),
      ( 200, 'MON', 'Monitor', 'Samsung', '19"', '', 'ARCHIVO', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 53'),
      ( 201, 'TEC', 'Mouse', 'Genius', '', '', 'ARCHIVO', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 53'),
      ( 202, 'TEC', 'Teclado', 'Genius', '', '', 'ARCHIVO', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 53'),
      ( 203, 'UPS', 'Regleta', 'Forza', '', '', 'ARCHIVO', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 53'),
      ( 204, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 10 PRO DE 64 BITS; PROCESADOR INTEL CORE I5-10400 DE 2.90 GHZ; MEMORIA RAM 16GB; DISCO SOLIDO M.2 1TB KINGSTON', 'COBRANZAS-1', 'ALISSON VARGAS', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 55'),
      ( 205, 'MON', 'Monitor', 'Asus', '22"', '', 'COBRANZAS-1', 'ALISSON VARGAS', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 55'),
      ( 206, 'TEC', 'Mouse', 'Genius', 'INALAMBRICO', '', 'COBRANZAS-1', 'ALISSON VARGAS', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 55'),
      ( 207, 'TEC', 'Teclado', 'Genius', 'INALAMBRICO', '', 'COBRANZAS-1', 'ALISSON VARGAS', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 55'),
      ( 208, 'TEC', 'Parlantes', '', '', '', 'COBRANZAS-1', 'ALISSON VARGAS', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 55. El PDF no indica marca'),
      ( 209, 'TEL', 'Telefono', 'Panasonic', '', 'Color negro', 'COBRANZAS-1', 'ALISSON VARGAS', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 55'),
      ( 210, 'UPS', 'Regleta', 'Forza', '', '', 'COBRANZAS-1', 'ALISSON VARGAS', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 55'),
      ( 211, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 10 PRO DE 64 BITS; PROCESADOR INTEL CORE I5-10400 DE 2.90 GHZ; MEMORIA RAM 16GB; DISCO SOLIDO M.2 1TB KINGSTON', 'COBRANZAS-2', 'CELESTE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 57'),
      ( 212, 'MON', 'Monitor', 'Asus', '22"', '', 'COBRANZAS-2', 'CELESTE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 57'),
      ( 213, 'TEC', 'Mouse', 'Genius', 'INALAMBRICO', '', 'COBRANZAS-2', 'CELESTE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 57'),
      ( 214, 'TEC', 'Teclado', 'Genius', 'INALAMBRICO', '', 'COBRANZAS-2', 'CELESTE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 57'),
      ( 215, 'IMP', 'Impresora', 'HP', 'LASEJET P1102w', '', 'COBRANZAS-2', 'CELESTE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 57'),
      ( 216, 'TEC', 'Parlantes', '', '', '', 'COBRANZAS-2', 'CELESTE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 57. El PDF no indica marca'),
      ( 217, 'RED', 'Switch', 'TP-Link', '10/100', '', 'COBRANZAS-2', 'CELESTE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 57'),
      ( 218, 'RED', 'Router', 'TP-Link', '3 ANTENAS', '', 'COBRANZAS-2', 'CELESTE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 57'),
      ( 219, 'TEL', 'Telefono', 'Panasonic', '', 'Color negro', 'COBRANZAS-2', 'CELESTE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 57'),
      ( 220, 'UPS', 'Regleta', 'Forza', '', '', 'COBRANZAS-2', 'CELESTE', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 57'),
      ( 221, 'LPT', 'Laptop', 'HP', '250 G5', 'WINDOWS WINDOWS 10 PRO DE 64 BITS; PROCESADOR AMD E2-7110 APU DE 1.80 GHZ; MEMORIA RAM 4GB; DISCO SOLIDO KINGSTON 480GB', 'COBRANZAS-3', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 61'),
      ( 222, 'TEC', 'Mouse', 'Knup', '', '', 'COBRANZAS-3', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 61'),
      ( 223, 'IMP', 'Impresora', 'Canon', '', '', 'COBRANZAS-3', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 61'),
      ( 224, 'TEL', 'Telefono', 'Panasonic', 'KX-T7705 - BLANCO', '', 'COBRANZAS-3', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 61'),
      ( 225, 'TEC', 'Adaptador USB a RJ45', '', '', '', 'COBRANZAS-3', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 61'),
      ( 226, 'UPS', 'Regleta', 'Forza', '', '', 'COBRANZAS-3', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 61'),
      ( 227, 'LPT', 'Laptop', 'HP', '250 DE 15.6" G10', 'WINDOWS WINDOWS 11 PRO DE 64 BITS; PROCESADOR INTEL CORE I3-1315U DE 1.20 GHZ; MEMORIA RAM 8GB; DISCO SOLIDO M.2 DE 500GB', 'COBRANZAS-4', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 64'),
      ( 228, 'TEC', 'Mouse', 'Knup', '', '', 'COBRANZAS-4', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 64'),
      ( 229, 'TEC', 'Adaptador USB a RJ45', '', '', '', 'COBRANZAS-4', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 64'),
      ( 230, 'IMP', 'Impresora', 'HP', 'LASERJET 1020', '', 'COBRANZAS-4', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 64'),
      ( 231, 'UPS', 'Regleta', 'Forza', '', '', 'COBRANZAS-4', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 64'),
      ( 232, 'LPT', 'Laptop', 'HP', '250 DE 15.6" G10', 'WINDOWS WINDOWS 11 PRO DE 64 BITS; PROCESADOR INTEL CORE I3-1315U DE 1.20 GHZ; MEMORIA RAM 8GB; DISCO SOLIDO M.2 DE 500GB', 'COBRANZAS-5', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 66'),
      ( 233, 'TEC', 'Adaptador USB a RJ45', '', '', '', 'COBRANZAS-5', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 66'),
      ( 234, 'UPS', 'Regleta', 'Forza', '', '', 'COBRANZAS-5', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 66'),
      ( 235, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 10 PRO DE 64 BITS; PROCESADOR INTEL CORE I5-4440 DE 3.10 GHZ; MEMORIA RAM 8GB; DISCO SOLIDO KINGSTON DE 480 GB', 'TRIBUNAL DE HONOR', 'DRA. MARIANA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 68'),
      ( 236, 'MON', 'Monitor', 'AOC', '19"', '', 'TRIBUNAL DE HONOR', 'DRA. MARIANA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 68'),
      ( 237, 'TEC', 'Mouse', 'Genius', '', '', 'TRIBUNAL DE HONOR', 'DRA. MARIANA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 68'),
      ( 238, 'TEC', 'Teclado', 'Soft', '', '', 'TRIBUNAL DE HONOR', 'DRA. MARIANA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 68'),
      ( 239, 'TEC', 'Parlantes', 'Soft', '', '', 'TRIBUNAL DE HONOR', 'DRA. MARIANA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 68'),
      ( 240, 'IMP', 'Impresora', 'HP', 'LASERJET 1020', '', 'TRIBUNAL DE HONOR', 'DRA. MARIANA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 68'),
      ( 241, 'TEL', 'Telefono', 'Panasonic', '', 'Color negro', 'TRIBUNAL DE HONOR', 'DRA. MARIANA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 68'),
      ( 242, 'RED', 'Router', 'TP-Link', '300MBPS', '', 'TRIBUNAL DE HONOR', 'DRA. MARIANA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 68'),
      ( 243, 'UPS', 'Regleta', 'Forza', '', '', 'TRIBUNAL DE HONOR', 'DRA. MARIANA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 68'),
      ( 244, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 10 PRO DE 64 BITS; PROCESADOR INTEL CORE I5-10400 DE 2.90 GHZ; MEMORIA RAM 8GB; DISCO SOLIDO FUTURE 500GB', 'TRIBUNAL DE HONOR-2', 'DRA. LEONILDA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 72'),
      ( 245, 'MON', 'Monitor', 'Samsung', '22"', '', 'TRIBUNAL DE HONOR-2', 'DRA. LEONILDA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 72'),
      ( 246, 'TEC', 'Mouse', 'Delux', '', '', 'TRIBUNAL DE HONOR-2', 'DRA. LEONILDA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 72'),
      ( 247, 'TEC', 'Teclado', 'Delux', '', '', 'TRIBUNAL DE HONOR-2', 'DRA. LEONILDA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 72'),
      ( 248, 'UPS', 'Regleta', 'Forza', '', '', 'TRIBUNAL DE HONOR-2', 'DRA. LEONILDA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 72'),
      ( 249, 'TEL', 'Telefono', 'Panasonic', '', 'Color negro', 'COCINA', 'SRA. CECILIA VACA', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 74'),
      ( 250, 'CPU', 'CPU de escritorio', '', '', 'WINDOWS WINDOWS 10 PRO DE 64 BITS; PROCESADOR INTEL CORE I5-10400 DE 2.90 GHZ; MEMORIA RAM 16GB; DISCO SOLIDO M.2 DE 1TB', 'SECRETARIA DE PRESIDENCIA', 'ING. BRENDA CORTEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 75'),
      ( 251, 'MON', 'Monitor', 'Asus', '22"', '', 'SECRETARIA DE PRESIDENCIA', 'ING. BRENDA CORTEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 75'),
      ( 252, 'TEC', 'Mouse', 'Tecson', '', '', 'SECRETARIA DE PRESIDENCIA', 'ING. BRENDA CORTEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 75'),
      ( 253, 'TEC', 'Teclado', 'Tecson', '', '', 'SECRETARIA DE PRESIDENCIA', 'ING. BRENDA CORTEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 75'),
      ( 254, 'TEC', 'Parlantes', 'Delux', '', '', 'SECRETARIA DE PRESIDENCIA', 'ING. BRENDA CORTEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 75'),
      ( 255, 'IMP', 'Impresora', 'HP', 'LASERJET M1132 MFP', '', 'SECRETARIA DE PRESIDENCIA', 'ING. BRENDA CORTEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 75'),
      ( 256, 'TEL', 'Telefono', 'Panasonic', '', 'Color negro', 'SECRETARIA DE PRESIDENCIA', 'ING. BRENDA CORTEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 75'),
      ( 257, 'TEL', 'Telefono', 'Panasonic', 'KX-FT984', '', 'SECRETARIA DE PRESIDENCIA', 'ING. BRENDA CORTEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 75'),
      ( 258, 'UPS', 'Estabilizador', 'Forza', '1.200VA', '', 'SECRETARIA DE PRESIDENCIA', 'ING. BRENDA CORTEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 75'),
      ( 259, 'RED', 'Router', 'TP-Link', 'GIGABITS AX20', '', 'SECRETARIA DE PRESIDENCIA', 'ING. BRENDA CORTEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 75'),
      ( 260, 'UPS', 'Regleta', 'Forza', '', '', 'SECRETARIA DE PRESIDENCIA', 'ING. BRENDA CORTEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 75'),
      ( 261, 'LPT', 'Laptop', 'HP', '250 DE 15.6" G10', 'WINDOWS WINDOWS 11 PRO DE 64 BITS; PROCESADOR INTEL CORE I3-1315U DE 1.20 GHZ; MEMORIA RAM 8GB; DISCO SOLIDO M.2 DE 500 GB', 'SECRETARIA DE PRESIDENCIA', 'ING. BRENDA CORTEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 79'),
      ( 262, 'UPS', 'Regleta', 'GCR', '', '', 'SECRETARIA DE PRESIDENCIA', 'ING. BRENDA CORTEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 79'),
      ( 263, 'LPT', 'Laptop', 'HP', '250 DE 14"', 'WINDOWS WINDOWS 11 PRO DE 64 BITS; PROCESADOR AMD RYZEN 3 - 3250U DE 2.60 GHZ; MEMORIA RAM 8GB; DISCO SOLIDO M.2 DE 500 GB SUPERSONIC', 'SECRETARIA DE PRESIDENCIA', 'ING. BRENDA CORTEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 81'),
      ( 264, 'LPT', 'Laptop', 'HP', '250 DE 14"', 'WINDOWS WINDOWS 11 PRO DE 64 BITS; PROCESADOR AMD RYZEN 3 - 3250U DE 2.60 GHZ; MEMORIA RAM 8GB; DISCO SOLIDO M.2 DE 500 GB SUPERSONIC', 'PRESIDENCIA', 'DR. JULIO EGUEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 82'),
      ( 265, 'IMP', 'Impresora', 'Epson', 'WORKFORCE PRO WF-6590', '', 'PRESIDENCIA', 'DR. JULIO EGUEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 82'),
      ( 266, 'TEL', 'Telefono', 'Panasonic', '', 'Color negro', 'PRESIDENCIA', 'DR. JULIO EGUEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 82'),
      ( 267, 'TEL', 'Telefono', 'Panasonic', '', 'Color negro', 'PRESIDENCIA', 'DR. JULIO EGUEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 82'),
      ( 268, 'UPS', 'Estabilizador', 'Forza', '1.200VA', '', 'PRESIDENCIA', 'DR. JULIO EGUEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 82'),
      ( 269, 'RED', 'Switch', 'TP-Link', '8 PUERTOS', '', 'PRESIDENCIA', 'DR. JULIO EGUEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 82'),
      ( 270, 'RED', 'Access point', 'Ubiquiti', 'BLANCO CON POE', '', 'PRESIDENCIA', 'DR. JULIO EGUEZ', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 82'),
      ( 271, 'RED', 'Router', 'Dahua', '4 ANTENAS GIGABITS', '', 'SALON AUDITORIO', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 86'),
      ( 272, 'PRY', 'Reproductor DVD', 'LG', '', '', 'SALON AUDITORIO', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 86'),
      ( 273, 'PRY', 'Proyector', 'Epson', 'X41+', '', 'SALON AUDITORIO', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 86'),
      ( 274, 'UPS', 'Estabilizador', 'Forza', '1.200VA', '', 'SALON AUDITORIO', '', 'Bueno', 'Migrado del PDF de inventario de computacion, pag. 86')
    ) as t(orden, categoria, denominacion, marca, modelo, caracteristicas,
           ubicacion, responsable, estado, observaciones)
    order by orden
  loop
    insert into public.activos (
      categoria, denominacion, marca, modelo, caracteristicas,
      ubicacion, responsable, estado, procedencia, valor,
      observaciones, verificacion, creado_por
    ) values (
      r.categoria, r.denominacion, r.marca, r.modelo, r.caracteristicas,
      r.ubicacion, r.responsable, r.estado, 'Sin dato', 0,
      r.observaciones, 'Pendiente', 'MIGRACION-COMPUTACION-2026'
    ) returning id into v_id;

    insert into public.movimientos (activo_id, tipo, detalle, usuario)
    values (v_id, 'ALTA',
            'Alta por migracion del inventario de equipos de computacion (PDF de Sistemas)',
            'MIGRACION-COMPUTACION-2026');

    v_total := v_total + 1;
  end loop;

  raise notice 'Bienes migrados: %', v_total;
end $$;

-- ------------------------------------------------------------
-- 3. Comprobacion
-- ------------------------------------------------------------
select c.nombre as categoria, count(*) as bienes
  from public.activos a
  join public.categorias c on c.codigo = a.categoria
 where a.creado_por = 'MIGRACION-COMPUTACION-2026'
 group by c.nombre
 order by bienes desc;

-- Bienes que conviene revisar a mano despues de migrar:
--   select codigo, denominacion, ubicacion, observaciones
--     from public.activos where observaciones ilike '%REVISAR%';
